# Generated by Django 3.0.7 on 2020-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='readingValue',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='bill',
            name='serial',
            field=models.CharField(max_length=12),
        ),
    ]
